language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"

# Install grunt-cli globally before installing all dependencies, including grunt
before_install:
  - npm install grunt-cli -g

# Running tests
script:
  - grunt lint
  - grunt build
  - grunt travis
